"""create emergency_sessions table

Revision ID: 94d6f0514e66
Revises: 
Create Date: 2026-09-13 00:58:12.843392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d6f0514e66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('name', sa.String(length=120), nullable=False, comment='Full name of the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address — used for login'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hash of the password — NEVER store plaintext'),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False, comment='User role — USER or ADMIN'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active status — False = soft deleted/disabled'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Account creation timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK → users.id — owner of this vehicle'),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False, comment='Unique vehicle registration number e.g. DL01AB1234'),
    sa.Column('owner_name', sa.String(length=120), nullable=False, comment='Name of the vehicle owner as on registration'),
    sa.Column('vehicle_type', sa.Enum('CAR', 'BIKE', 'SUV', 'VAN', 'TRUCK', 'OTHER', name='vehicletype'), nullable=False, comment='Type of vehicle: CAR, BIKE, SUV, VAN, TRUCK, OTHER'),
    sa.Column('vehicle_color', sa.String(length=50), nullable=False, comment='Color of the vehicle'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether vehicle has been verified by an admin'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when vehicle was registered (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    op.create_table('emergency_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK → users.id — owner of this emergency session'),
    sa.Column('vehicle_id', sa.Integer(), nullable=False, comment='FK → vehicles.id — vehicle associated with this SOS'),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'EXPIRED', name='emergencystatus'), nullable=False, comment='Current lifecycle status of the session'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='Server time when SOS was activated'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='Server time when user ended the session (null if still active)'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Server-computed expiry time — session auto-expires after this'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_sessions_id'), 'emergency_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_sessions_status'), 'emergency_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_emergency_sessions_user_id'), 'emergency_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_emergency_sessions_vehicle_id'), 'emergency_sessions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_sessions_vehicle_id'), table_name='emergency_sessions')
    op.drop_index(op.f('ix_emergency_sessions_user_id'), table_name='emergency_sessions')
    op.drop_index(op.f('ix_emergency_sessions_status'), table_name='emergency_sessions')
    op.drop_index(op.f('ix_emergency_sessions_id'), table_name='emergency_sessions')
    op.drop_table('emergency_sessions')
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
